/**
 * Shared Codex CLI config constants.
 * Imported by both install-git-hooks.ts and core.ts.
 */

export const CODEX_CONFIG_TOML = `# Codex CLI configuration — generated by Harness Engineering and Orchestrator
# Notification hooks receive JSON on stdin and run asynchronously (non-blocking).

[notify]
command = "bun .harness/runtime/hooks/check-guardian.ts --codex"
`

export const CODEX_GUARDIAN_RULES = `# Codex CLI execpolicy rules — generated by Harness Engineering and Orchestrator
# Format: Starlark-style rules evaluated top-down. First match wins.
# Actions: forbidden (block), prompt (ask user), allow (pass through).

# G2 / bypass prevention: block --no-verify flag
forbidden("git commit --no-verify")
forbidden("git push --no-verify")

# G9: LEARNING.md must not be staged
forbidden("git add LEARNING.md")
forbidden("git add ./LEARNING.md")

# Dangerous staging commands: block git add . and git add -A
forbidden("git add .")
forbidden("git add -A")
`
