import { existsSync, readFileSync, writeFileSync } from "fs"
import type { ProjectState } from "../types"

type EnvBlock = {
  block: string
  id: string
}

function buildBlocks(state: ProjectState): EnvBlock[] {
  const blocks: EnvBlock[] = [
    {
      id: "NODE_ENV",
      block: `# .env.local
# Local-only environment scaffold generated by Harness.
# Fill values milestone by milestone as real integrations are implemented.
# Do not commit this file.

# Core
NODE_ENV=development
APP_URL=http://localhost:3000
DEPLOY_TARGET=
DEPLOY_ENV=development`,
    },
  ]

  if (state.projectInfo.types.includes("web-app")) {
    blocks.push({
      id: "WEB_DEV_PORT",
      block: `# Web surface
WEB_DEV_PORT=3000
WEB_PUBLIC_URL=http://localhost:3000`,
    })
  }

  if (state.projectInfo.types.includes("ios-app")) {
    blocks.push({
      id: "IOS_BUNDLE_ID",
      block: `# iOS surface
IOS_BUNDLE_ID=com.example.${state.projectInfo.name || "app"}
IOS_APP_SCHEME=${(state.projectInfo.displayName || state.projectInfo.name || "App").replace(/\s+/g, "")}`,
    })
  }

  if (state.projectInfo.types.includes("cli")) {
    blocks.push({
      id: "CLI_BINARY_NAME",
      block: `# CLI surface
CLI_BINARY_NAME=${state.projectInfo.name || "app-cli"}`,
    })
  }

  if (state.projectInfo.types.includes("agent")) {
    blocks.push({
      id: "AGENT_PORT",
      block: `# Agent surface
AGENT_PORT=8787
AGENT_SKILL_CATALOG=./SKILLS.md
AGENT_API_WRAPPER_DIR=packages/shared/api`,
    })
  }

  if (state.projectInfo.types.includes("desktop")) {
    blocks.push({
      id: "DESKTOP_DEV_PORT",
      block: `# Desktop surface
DESKTOP_DEV_PORT=3001`,
    })
  }

  if (["openai", "both", "vercel-ai-sdk"].includes(state.projectInfo.aiProvider)) {
    blocks.push({
      id: "OPENAI_API_KEY",
      block: `# OpenAI
OPENAI_API_KEY=`,
    })
  }

  if (["anthropic", "both"].includes(state.projectInfo.aiProvider)) {
    blocks.push({
      id: "ANTHROPIC_API_KEY",
      block: `# Anthropic
ANTHROPIC_API_KEY=`,
    })
  }

  if (state.projectInfo.aiProvider === "vercel-ai-sdk") {
    blocks.push({
      id: "AI_GATEWAY_API_KEY",
      block: `# Vercel AI SDK / Gateway
AI_GATEWAY_API_KEY=`,
    })
  }

  blocks.push({
    id: "DATABASE_URL",
    block: `# Optional data layer placeholders
DATABASE_URL=
AUTH_SECRET=
REDIS_URL=`,
  })

  return blocks
}

export function ensureEnvLocalSkeleton(state: ProjectState): { changed: boolean; created: boolean } {
  const path = ".env.local"
  const blocks = buildBlocks(state)

  if (!existsSync(path)) {
    writeFileSync(path, `${blocks.map(block => block.block).join("\n\n")}\n`)
    return { changed: true, created: true }
  }

  let current = readFileSync(path, "utf-8")
  let changed = false

  for (const block of blocks) {
    if (current.includes(`${block.id}=`)) continue
    current = `${current.trimEnd()}\n\n${block.block}\n`
    changed = true
  }

  if (changed) {
    writeFileSync(path, current)
  }

  return { changed, created: false }
}
